ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("web/", include("web.urls", namespace="web")),
        path("main/", include("main.urls", namespace="main")),
        path("", include("products.urls", namespace="products")),
        path("orders/", include("orders.urls", namespace="orders")),
        path('tinymce/', include('tinymce.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

main/urls.py
app_name = "main"

urlpatterns = []

orders/urls.py
app_name = "orders"

urlpatterns = []

products/urls.py
from django.urls import path

from . import views


app_name = "products"

urlpatterns = [
    path("", views.IndexListView.as_view(), name="index"),
    path('categories/', views.CategoryView.as_view(), name='category'),
    path("products/", views.ProductList.as_view(), name="products"),
    path("subcategorie/", views.SubCategoryView.as_view(), name="subcategory"),
]

web/urls.py
app_name = "web"

urlpatterns = []

main/models.py
# Create your models here.

orders/models.py
# Create your models here.

products/models.py
from django.db import models
from django.utils.text import slugify
from tinymce.models import HTMLField


class TopCategory(models.Model):
    top_category = models.CharField(max_length=50,blank=True,null=True)

    class Meta:
        verbose_name_plural = "TopCategories"

    def __str__(self):
        return self.top_category

class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='subcategory')
    category = models.ForeignKey(Category, verbose_name=("category"), on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "SubCategories"


class Product(models.Model):
    top_category = models.ForeignKey(TopCategory, verbose_name="topcategories", on_delete=models.CASCADE,blank=True,null=True)
    category = models.ForeignKey(SubCategory, verbose_name=("subcategory"), on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    image = models.ImageField(upload_to="products")
    description = HTMLField(null=True, blank=True)
    price = models.FloatField()

    def _str_(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_topcategory(self):
        return TopCategory.objects.filter(top_category=self)


class ProductImage(models.Model):
    name = models.ForeignKey(Product, verbose_name=("productimage"), on_delete=models.CASCADE)
    image = models.ImageField(upload_to='productimages')

    def _str_(self):
        return self.name

web/models.py
# Create your models here.

main/views.py
# Create your views here.

orders/views.py
# Create your views here.

products/views.py
from django.views.generic import ListView
from django.views.generic import TemplateView

from .models import Category
from .models import Product
from .models import SubCategory
from .models import TopCategory

class IndexListView(ListView):
    model = Product
    template_name = "products/index.html"
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['subcategories'] = SubCategory.objects.all()
        context['subcategories'] = SubCategory.objects.all()
        context['top_categories'] =  TopCategory.objects.all()
        return context


class CategoryView(TemplateView):
    template_name = "products/categorie_list.html"


class SubCategoryView(TemplateView):
    template_name = "products/subcategorie_list.html"


class ProductList(ListView):
    model = Product
    template_name = "products/products_list.html"

web/views.py
# Create your views here.

templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="description">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Title Of Site -->
    <title>Hema - Multipurpose eCommerce Bootstrap 5 Html Template</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static "assets/images/favicon.png" %}" />
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{% static "assets/css/plugins.css" %}">
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="{% static "assets/css/style-min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/responsive.css" %}">
</head>

<body class="template-index index-demo1">



    {% include 'products/partials/header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'products/partials/footer.html' %}

    <!-- Including Jquery/Javascript -->
    <!-- Plugins JS -->
    <script src="{% static "assets/js/plugins.js" %}"></script>
    <!-- Main JS -->
    <script src="{% static "assets/js/main.js" %}"></script>
    <!--Newsletter Modal Cookies-->
    <script>
        $(window).ready(function () {
            setTimeout(function () {
                $('#newsletter_modal').modal("show");
            }, 7000);
        });
    </script>
    <!--End Newsletter Modal Cookies-->

    </div>
    <!--End Page Wrapper-->
</body>

</html>

templates/products/categorie_list.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}

 <!--Popular Categories-->
 <section class="section collection-slider pb-0">
  <div class="container">
      <div class="section-header">
          <p class="mb-2 mt-0">Shop by category</p>
          <h2>Popular Collections</h2>
      </div>

      <div class="collection-slider-5items gp15 arwOut5 hov-arrow">
        {% for category in categories %}
          <div class="category-item zoomscal-hov">
              <a href="shop-left-sidebar.html" class="category-link clr-none">
                  <div class="zoom-scal zoom-scal-nopb rounded-3"><img class="blur-up lazyload"
                          data-src="{{category.image.url}}"
                          src="{{category.image.url}}" alt="Men's Jakets"
                          title="Men's Jakets" width="365" height="365" /></div>
                  <div class="details mt-3 text-center">
                      <h4 class="category-title mb-0">{{category.name }}</h4>
                      <p class="counts">20 Products</p>
                  </div>
              </a>
        </div>
         {% endfor %}
      </div>
  </div>
</section>
<!--End Popular Categories-->
{% endblock %}

templates/products/partials/footer.html
{% load static %}
<!--Footer-->
<div class="footer">
    <div class="newsletterbg clearfix"> 
        <div class="container">
            <form action="#" method="post" class="footer-newsletter">
                <div class="row align-items-center">
                    <div class="col-12 col-sm-12 col-md-6 col-lg-6 mb-3 mb-md-0">
                        <label class="h3 mb-1 clr-none">Sign Up Our Newsletter & Get 10% OFF</label>
                        <p>Sign up to stay in the loop. Receive updates, access to exclusive deals, and more.</p>
                    </div>
                    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
                        <div class="input-group">
                            <input type="email" class="form-control input-group-field newsletter-input" name="email"
                                value="" placeholder="Enter your email address..." required />
                            <button type="submit" class="input-group-btn btn btn-secondary newsletter-submit"
                                name="commit">Subscribe</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="footer-top clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                    <h4 class="h4">Informations</h4>
                    <ul>
                        <li><a href="my-account.html">My Account</a></li>
                        <li><a href="aboutus-style1.html">About us</a></li>
                        <li><a href="login.html">Login</a></li>
                        <li><a href="privacy-policy.html">Privacy policy</a></li>
                        <li><a href="#">Terms &amp; condition</a></li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                    <h4 class="h4">Quick Shop</h4>
                    <ul>
                        <li><a href="#">Bags &amp; Accessories</a></li>
                        <li><a href="#">Tools &amp; Parts</a></li>
                        <li><a href="#">Vegetables</a></li>
                        <li><a href="#">Jewelry</a></li>
                        <li><a href="#">Cosmetics</a></li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                    <h4 class="h4">Customer Services</h4>
                    <ul>
                        <li><a href="#">Request Personal Data</a></li>
                        <li><a href="faqs-style1.html">FAQ's</a></li>
                        <li><a href="contact-style1.html">Contact Us</a></li>
                        <li><a href="#">Orders and Returns</a></li>
                        <li><a href="#">Support Center</a></li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-contact">
                    <h4 class="h4">Contact Us</h4>
                    <p class="address d-flex"><i class="icon anm anm-map-marker-al pt-1"></i> 55 Gallaxy Enque, 2568
                        steet, 23568 NY</p>
                    <p class="phone d-flex align-items-center"><i class="icon anm anm-phone-l"></i> <b
                            class="me-1 d-none">Phone:</b> <a href="tel:401234567890">(+40) 123 456 7890</a></p>
                    <p class="email d-flex align-items-center"><i class="icon anm anm-envelope-l"></i> <b
                            class="me-1 d-none">Email:</b> <a href="mailto:info@example.com">info@example.com</a></p>
                    <ul class="list-inline social-icons mt-3">
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                title="Facebook"><i class="icon anm anm-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                title="Twitter"><i class="icon anm anm-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                title="Pinterest"><i class="icon anm anm-pinterest-p"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                title="Linkedin"><i class="icon anm anm-linkedin-in"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                title="Instagram"><i class="icon anm anm-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                title="Youtube"><i class="icon anm anm-youtube"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom clearfix">
        <div class="container">
            <div class="d-flex-center flex-column justify-content-md-between flex-md-row-reverse">
                <ul class="payment-icons d-flex-center mb-2 mb-md-0">
                    <li><i class="icon anm anm-cc-visa"></i></li>
                    <li><i class="icon anm anm-cc-mastercard"></i></li>
                    <li><i class="icon anm anm-cc-amex"></i></li>
                    <li><i class="icon anm anm-cc-paypal"></i></li>
                    <li><i class="icon anm anm-cc-discover"></i></li>
                    <li><i class="icon anm anm-cc-stripe"></i></li>
                    <li><i class="icon anm anm-cc-jcb"></i></li>
                </ul>
                <div class="copytext">&copy; 2023 Hema. All Rights Reserved.</div>
            </div>
        </div>
    </div>
</div>
<!--End Footer-->

templates/products/products_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Product</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">  

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #516BEB;">
      <div class="container-fluid">
        <a class="navbar-brand fw-bold" href="#">Coding</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Products
              </a>
              <div class="dropdown-menu">
                <ul>
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="{% url "products:category" %}">Categorie</a></li>
                  <li><a class="dropdown-item" href="{% url "products:subcategory" %}">Subcatogrie</a></li>
         
                </ul>
               
              
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          {% comment %} <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light" type="submit">Search</button>
          </form> {% endcomment %}
        </div>
      </div>
    </nav>
    <style>
      body{
        overflow-x:hidden;
      }
      .navbar-brand {
        font-size: 1.4em;
      }
      .navbar-dark .navbar-nav a.nav-link {
        color: #ffffff;
        font-size: 1.1em;
      }
      .dropdown-menu {
        box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
        border: none;
        border-radius: 0;
        padding: 0.7em;
      }
      @media only screen and (min-width: 992px) {
        .dropdown:hover .dropdown-menu {
          display: flex;
        }
        .dropdown-menu.show {
          display: flex;
        }
      }
      .dropdown-menu ul {
        list-style: none;
        padding: 0;
      }
      .dropdown-menu li .dropdown-item {
        color: gray;
        font-size: 1em;
        padding: 0.5em 1em;
      }
      .dropdown-menu li .dropdown-item:hover {
        background-color: #f1f1f1;
      }
      .dropdown-menu li:first-child a {
        font-weight: bold;
        font-size: 1.1em;
        text-transform: uppercase;
        color: #516beb;
      }
      .dropdown-menu li:first-child a:hover {
        background-color: #f1f1f1;
      }
      @media only screen and (max-width: 992px) {
        .dropdown-menu.show {
          flex-wrap: wrap;
          max-height: 350px;
          overflow-y: scroll;
        }
      }
      @media only screen and (min-width: 992px) and (max-width: 1140px) {
        .dropdown:hover .dropdown-menu {
          width: 40vw;
          flex-wrap: wrap;
        }
      }
      
      .dropdown-menu {
        border-radius: 0;
        border: none;
        padding: 0.5em;
        box-shadow: 0 3px 6px rgba(0, 0, 0, 0.23);
      }
      .dropdown-menu ul {
        list-style: none;
        padding: 0;
      }
      
      .dropdown-menu li a {
        color: gray;
        padding: 0.5em 1em;
      }
      .dropdown-menu li:first-child a {
        font-weight: bold;
        font-size: 1.1em;
        color: #516beb;
      }
      @media screen and (min-width: 993px) {
        .dropdown:hover .dropdown-menu {
          display: flex;
        }
        .dropdown-menu.show {
          display: flex;
        }
      }
      @media screen and (max-width: 992px) {
        .dropdown-menu.show {
          max-height: 60vh;
          overflow-y: scroll;
        }
      }
      
    </style>
    
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-5 ms-auto">
      {% for products in object_list %}

      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
        <div class="card">
          <img src="{{products.image.url}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{ products.name }}</h5>
            <p class="card-text">{{products.price}}</p>
          </div>
        </div>
      </div>
 

      {% endfor %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>

templates/products/subcategorie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">  

</head>
<body>



    <div class="card mt-5 ms-5" style="width: 18rem;">
      {% for products in object_list %}

      <img src="{{products.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ products.name }}</h5>
        <p class="card-text">{{products.price}}</p>
        {% comment %} <a href="#" class="btn btn-primary">Go somewhere</a> {% endcomment %}
      </div>
      {% endfor %}

    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>